### ISSUE TITLE
导出报错

### ISSUE THREAD

**Issue by hanxi** [FGadvancer/ruapi-generate-md#2]
```txt
generate start at  2023-08-21 22:59:53.467774872 +0800 CST m=+0.001818234
panic: json: cannot unmarshal number into Go struct field Header.request.params.jsonDesc.value of type string

goroutine 1 [running]:
github.com/ruapi-generate-md/internal.generateOnePageMarkDown({0xc0001af000?, 0x7?}, {0x9543a0, 0x0, 0x0}, {0xc0000e4648, 0x15}, {0xc000192488, 0x7})
        /home/hanxi/tmp/ruapi-generate-md/internal/single_catalog_generator.go:116 +0xf0b
github.com/ruapi-generate-md/internal.GeneratePageByItemID({0x753a41, 0x2}, {0x7ffcd8c55c9d, 0x4})
        /home/hanxi/tmp/ruapi-generate-md/internal/catlaog_page_generator.go:46 +0x325
main.main()
        /home/hanxi/tmp/ruapi-generate-md/cmd/main.go:15 +0x165
  adding: rank/主页.md (deflated 49%)
  adding: rank/心跳检测.md (deflated 49%)
```

**Comment by FGadvancer** [comment]
There was a problem with the header arguments' type, I have fixed it. You can perform git pull and try again.If you encounter any issues, please provide me with a test file to assist in better troubleshooting and fixing. Thank you.
